//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.21 at 11:24:30 PM CDT 
//


package gov.va.legoEdit.model.schemaModel;

import com.sleepycat.persist.model.Persistent;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="assertionUUID" type="{}UUID"/>
 *         &lt;element ref="{}discernible"/>
 *         &lt;element ref="{}qualifier"/>
 *         &lt;element ref="{}value"/>
 *         &lt;element ref="{}timing" minOccurs="0"/>
 *         &lt;element ref="{}assertionComponents" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "assertionUUID",
    "discernible",
    "qualifier",
    "value",
    "timing",
    "assertionComponents"
})
@XmlRootElement(name = "assertion")
@Persistent
public class Assertion {

    @XmlElement(required = true)
    protected String assertionUUID;
    @XmlElement(required = true)
    protected Discernible discernible;
    @XmlElement(required = true)
    protected Qualifier qualifier;
    @XmlElement(required = true)
    protected Value value;
    protected Timing timing;
    protected AssertionComponents assertionComponents;

    /**
     * Gets the value of the assertionUUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssertionUUID() {
        return assertionUUID;
    }

    /**
     * Sets the value of the assertionUUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssertionUUID(String value) {
        this.assertionUUID = value;
    }

    /**
     * Gets the value of the discernible property.
     * 
     * @return
     *     possible object is
     *     {@link Discernible }
     *     
     */
    public Discernible getDiscernible() {
        return discernible;
    }

    /**
     * Sets the value of the discernible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Discernible }
     *     
     */
    public void setDiscernible(Discernible value) {
        this.discernible = value;
    }

    /**
     * Gets the value of the qualifier property.
     * 
     * @return
     *     possible object is
     *     {@link Qualifier }
     *     
     */
    public Qualifier getQualifier() {
        return qualifier;
    }

    /**
     * Sets the value of the qualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Qualifier }
     *     
     */
    public void setQualifier(Qualifier value) {
        this.qualifier = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link Value }
     *     
     */
    public Value getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Value }
     *     
     */
    public void setValue(Value value) {
        this.value = value;
    }

    /**
     * Gets the value of the timing property.
     * 
     * @return
     *     possible object is
     *     {@link Timing }
     *     
     */
    public Timing getTiming() {
        return timing;
    }

    /**
     * Sets the value of the timing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timing }
     *     
     */
    public void setTiming(Timing value) {
        this.timing = value;
    }

    /**
     * Gets the value of the assertionComponents property.
     * 
     * @return
     *     possible object is
     *     {@link AssertionComponents }
     *     
     */
    public AssertionComponents getAssertionComponents() {
        return assertionComponents;
    }

    /**
     * Sets the value of the assertionComponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssertionComponents }
     *     
     */
    public void setAssertionComponents(AssertionComponents value) {
        this.assertionComponents = value;
    }

}
