//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.21 at 11:24:30 PM CDT 
//


package gov.va.legoEdit.model.schemaModel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import com.sleepycat.persist.model.Persistent;


/**
 * <p>Java class for bound complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bound">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="numericPoint" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *           &lt;element name="stringPoint" type="{}measurementString"/>
 *           &lt;element ref="{}pointPair"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="inclusive" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bound", propOrder = {
    "numericPoint",
    "stringPoint",
    "pointPair"
})
@Persistent
public class Bound {

    protected Float numericPoint;
    protected MeasurementString stringPoint;
    protected PointPair pointPair;
    @XmlAttribute(name = "inclusive")
    protected Boolean inclusive;

    /**
     * Gets the value of the numericPoint property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getNumericPoint() {
        return numericPoint;
    }

    /**
     * Sets the value of the numericPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setNumericPoint(Float value) {
        this.numericPoint = value;
    }

    /**
     * Gets the value of the stringPoint property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementString }
     *     
     */
    public MeasurementString getStringPoint() {
        return stringPoint;
    }

    /**
     * Sets the value of the stringPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementString }
     *     
     */
    public void setStringPoint(MeasurementString value) {
        this.stringPoint = value;
    }

    /**
     * Gets the value of the pointPair property.
     * 
     * @return
     *     possible object is
     *     {@link PointPair }
     *     
     */
    public PointPair getPointPair() {
        return pointPair;
    }

    /**
     * Sets the value of the pointPair property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointPair }
     *     
     */
    public void setPointPair(PointPair value) {
        this.pointPair = value;
    }

    /**
     * Gets the value of the inclusive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInclusive() {
        return inclusive;
    }

    /**
     * Sets the value of the inclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInclusive(Boolean value) {
        this.inclusive = value;
    }

}
