//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 01:50:51 PM CST 
//


package gov.va.legoEdit.model.schemaModel;

import com.sleepycat.persist.model.Persistent;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}units" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="stringPoint" type="{}measurementString"/>
 *           &lt;element name="numericPoint" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *           &lt;element ref="{}interval"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "units",
    "stringPoint",
    "numericPoint",
    "interval"
})
@XmlRootElement(name = "measurement")
@Persistent
public class Measurement {

    protected Units units;
    protected MeasurementString stringPoint;
    protected Float numericPoint;
    protected Interval interval;

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link Units }
     *     
     */
    public Units getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link Units }
     *     
     */
    public void setUnits(Units value) {
        this.units = value;
    }

    /**
     * Gets the value of the stringPoint property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementString }
     *     
     */
    public MeasurementString getStringPoint() {
        return stringPoint;
    }

    /**
     * Sets the value of the stringPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementString }
     *     
     */
    public void setStringPoint(MeasurementString value) {
        this.stringPoint = value;
    }

    /**
     * Gets the value of the numericPoint property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getNumericPoint() {
        return numericPoint;
    }

    /**
     * Sets the value of the numericPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setNumericPoint(Float value) {
        this.numericPoint = value;
    }

    /**
     * Gets the value of the interval property.
     * 
     * @return
     *     possible object is
     *     {@link Interval }
     *     
     */
    public Interval getInterval() {
        return interval;
    }

    /**
     * Sets the value of the interval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interval }
     *     
     */
    public void setInterval(Interval value) {
        this.interval = value;
    }

}
