//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.21 at 11:24:30 PM CDT 
//


package gov.va.legoEdit.model.schemaModel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.va.legoEdit.model.schemaModel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.va.legoEdit.model.schemaModel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Stamp }
     * 
     */
    public Stamp createStamp() {
        return new Stamp();
    }

    /**
     * Create an instance of {@link ConceptAndRel }
     * 
     */
    public ConceptAndRel createConceptAndRel() {
        return new ConceptAndRel();
    }

    /**
     * Create an instance of {@link Concept }
     * 
     */
    public Concept createConcept() {
        return new Concept();
    }

    /**
     * Create an instance of {@link Rel }
     * 
     */
    public Rel createRel() {
        return new Rel();
    }

    /**
     * Create an instance of {@link Measurement }
     * 
     */
    public Measurement createMeasurement() {
        return new Measurement();
    }

    /**
     * Create an instance of {@link Units }
     * 
     */
    public Units createUnits() {
        return new Units();
    }

    /**
     * Create an instance of {@link Interval }
     * 
     */
    public Interval createInterval() {
        return new Interval();
    }

    /**
     * Create an instance of {@link Bound }
     * 
     */
    public Bound createBound() {
        return new Bound();
    }

    /**
     * Create an instance of {@link LegoList }
     * 
     */
    public LegoList createLegoList() {
        return new LegoList();
    }

    /**
     * Create an instance of {@link Lego }
     * 
     */
    public Lego createLego() {
        return new Lego();
    }

    /**
     * Create an instance of {@link Pncs }
     * 
     */
    public Pncs createPncs() {
        return new Pncs();
    }

    /**
     * Create an instance of {@link Assertion }
     * 
     */
    public Assertion createAssertion() {
        return new Assertion();
    }

    /**
     * Create an instance of {@link Discernible }
     * 
     */
    public Discernible createDiscernible() {
        return new Discernible();
    }

    /**
     * Create an instance of {@link Qualifier }
     * 
     */
    public Qualifier createQualifier() {
        return new Qualifier();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link Timing }
     * 
     */
    public Timing createTiming() {
        return new Timing();
    }

    /**
     * Create an instance of {@link AssertionComponents }
     * 
     */
    public AssertionComponents createAssertionComponents() {
        return new AssertionComponents();
    }

    /**
     * Create an instance of {@link AssertionComponent }
     * 
     */
    public AssertionComponent createAssertionComponent() {
        return new AssertionComponent();
    }

    /**
     * Create an instance of {@link PointPair }
     * 
     */
    public PointPair createPointPair() {
        return new PointPair();
    }

}
