//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.10 at 05:50:42 PM CST 
//


package gov.va.legoEdit.model.schemaModel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import com.sleepycat.persist.model.Persistent;


/**
 * <p>Java class for point complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="point">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="numericValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *           &lt;element name="stringConstant" type="{}measurementConstant"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "point", propOrder = {
    "numericValue",
    "stringConstant"
})
@Persistent
public class Point {

    protected Float numericValue;
    protected MeasurementConstant stringConstant;

    /**
     * Gets the value of the numericValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getNumericValue() {
        return numericValue;
    }

    /**
     * Sets the value of the numericValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setNumericValue(Float value) {
        this.numericValue = value;
    }

    /**
     * Gets the value of the stringConstant property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementConstant }
     *     
     */
    public MeasurementConstant getStringConstant() {
        return stringConstant;
    }

    /**
     * Sets the value of the stringConstant property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementConstant }
     *     
     */
    public void setStringConstant(MeasurementConstant value) {
        this.stringConstant = value;
    }

}
