//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 01:50:51 PM CST 
//


package gov.va.legoEdit.model.schemaModel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.sleepycat.persist.model.Persistent;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="greaterThan" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="lessThan" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "greaterThan",
    "lessThan"
})
@XmlRootElement(name = "pointPair")
@Persistent
public class PointPair {

    protected float greaterThan;
    protected float lessThan;

    /**
     * Gets the value of the greaterThan property.
     * 
     */
    public float getGreaterThan() {
        return greaterThan;
    }

    /**
     * Sets the value of the greaterThan property.
     * 
     */
    public void setGreaterThan(float value) {
        this.greaterThan = value;
    }

    /**
     * Gets the value of the lessThan property.
     * 
     */
    public float getLessThan() {
        return lessThan;
    }

    /**
     * Sets the value of the lessThan property.
     * 
     */
    public void setLessThan(float value) {
        this.lessThan = value;
    }

}
